#!/bin/bash
red='\033[1;31m' #31
grn='\033[1;32m' #32
yel='\033[1;33m' #33
blu='\033[1;36m' #36
pnk='\033[1;35m'
clr='\033[0m'

if [ -z $1 ]; then
  echo
  echo -e " ${yel}seek utility version 1.0 by Chris, 2019"
  echo -e " ${grn}usage: ${blu}seek ${pnk}term ${blu}[from_what_directory]"
  echo -e " ${grn}ex   : ${blu}seek ${pnk}foo ${blu}~/bar"
  echo -e " ${grn}ex2  : ${blu}seek ${pnk}foo${clr}"
  echo
  exit 1
fi


if [ -z $2 ]; then
  searchfrom=$2
else
  searchfrom=$PWD
fi

grep -rn --color=always $searchfrom $1
