#!/bin/bash

Pre-reqs:
===========================
#GIT and Compiler dependencies
sudo apt update
sudo apt upgrade
sudo apt install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install -y g++-mingw-w64-x86-64
sudo apt install -y unzip

#AEM Dependencies
sudo apt install -y jq software-properties-common curl
sudo apt update > /dev/null 2>&1
sudo apt install -y pwgen build-essential libssl-dev libboost-all-dev libqrencode-dev libminiupnpc-dev libevent-2.0-5
sudo add-apt-repository -y ppa:bitcoin/bitcoin
sudo apt update
sudo apt install -y libdb5.3-dev libdb5.3++-dev
sudo apt install -y libzmq5 libboost-system1.58.0 libboost-filesystem1.58.0 libboost-program-options1.58.0 libboost-thread1.58.0 libboost-chrono1.58.0 libminiupnpc10 libevent-pthreads-2.0-5 unzip

# QT Libs and files
sudo apt-get install -y libqt5webkit5-dev qtscript5-dev qtquick1-5-dev libqt5help5 qttools5-dev qttools5-private-dev qtdeclarative5-private-dev qtscript5-private-dev qtdeclarative5-dev-tools qtbase5-private-dev libqt5xmlpatterns5-dev qtxmlpatterns5-dev-tools qttools5-dev-tools


# Compiling for WINDOWS x32:  #
# =========================== #
sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install g++-mingw-w64-x86-64
sudo apt install unzip
sudo update-alternatives --config x86_64-w64-mingw32-g++ #POSIX will be the default one
cd Atheneum/depends/
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/opt/local
make


# Compiling for WINDOWS x64:  #
# =========================== #
sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install g++-mingw-w64-x86-64
sudo apt install unzip
sudo update-alternatives --config x86_64-w64-mingw32-g++ #POSIX will be the default one
cd Atheneum/depends/
cd depends
make HOST=i686-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/
make

# =========================== #
# Compiling for Ubuntu        #
# =========================== #
sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install unzip
cd Atheneum
./autogen.sh
./configure --with-gui=qt5    (if you want to build daemon, use --without-gui)
make


