#!/bin/bash

#GIT and Compiler dependencies
sudo apt update
sudo apt upgrade
sudo apt install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install -y g++-mingw-w64-x86-64
sudo apt install -y unzip

#AEM Dependencies
sudo apt install -y jq software-properties-common curl > /dev/null 2>&1
sudo apt update > /dev/null 2>&1
sudo apt install -y pwgen build-essential libssl-dev libboost-all-dev libqrencode-dev libminiupnpc-dev libevent-2.0-5 > /dev/null 2>&1
sudo add-apt-repository -y ppa:bitcoin/bitcoin > /dev/null 2>&1
sudo apt update > /dev/null 2>&1
sudo apt install -y libdb5.3-dev libdb5.3++-dev
sudo apt install -y libzmq5 libboost-system1.58.0 libboost-filesystem1.58.0 libboost-program-options1.58.0 libboost-thread1.58.0 libboost-chrono1.58.0 libminiupnpc10 libevent-pthreads-2.0-5 unzip > /dev/null 2>&1

# QT Libs and files
sudo apt-get install -y libqt5webkit5-dev qtscript5-dev qtquick1-5-dev libqt5help5 qttools5-dev qttools5-private-dev qtdeclarative5-private-dev qtscript5-private-dev qtdeclarative5-dev-tools qtbase5-private-dev libqt5xmlpatterns5-dev qtxmlpatterns5-dev-tools qttools5-dev-tools

